webtalk_init -webtalk_dir /home/shubham/Vivado_Exercises/polar_2_ex/polar_2_ex.sim/sim_1/behav/xsim/xsim.dir/example_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jan 13 18:43:27 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211528478_1777544339_0_200" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5e4f2d92-86e6-4fb3-87f3-5afa9b6d9751" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bbbaa0e20ea84fbb9f10de87d8f5d209" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4165.903 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "9 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "142724_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3094600285 -regid "211528478_1777544339_0_200" -xml /home/shubham/Vivado_Exercises/polar_2_ex/polar_2_ex.sim/sim_1/behav/xsim/xsim.dir/example_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/shubham/Vivado_Exercises/polar_2_ex/polar_2_ex.sim/sim_1/behav/xsim/xsim.dir/example_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/shubham/Vivado_Exercises/polar_2_ex/polar_2_ex.sim/sim_1/behav/xsim/xsim.dir/example_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
