#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : ps_example.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jan 13 11:01:11 IST 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: ps_example.sh [-help]
# usage: ps_example.sh [-lib_map_path]
# usage: ps_example.sh [-noclean_files]
# usage: ps_example.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'ps_example.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm xlconstant_v1_1_5 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_18 axis_subset_converter_v1_1_18 axis_broadcaster_v1_1_17 axis_data_fifo_v2_0_0 ecc_v2_0_12 fec_5g_common_v1_1_0 polar_v1_0_2 axis_clock_converter_v1_1_19 axis_dwidth_converter_v1_1_17 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_20 xlslice_v1_0_1 xbip_utils_v3_0_9 c_reg_fd_v12_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_5 xbip_dsp48_addsub_v3_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 c_gate_bit_v12_0_5 xbip_counter_v3_0_5 c_counter_binary_v12_0_12 microblaze_v11_0_0 lmb_v10_v3_0_9 lmb_bram_if_cntlr_v4_0_15 blk_mem_gen_v8_4_2 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_18 fifo_generator_v13_2_3 axi_data_fifo_v2_1_17 axi_crossbar_v2_1_19 axi_clock_converter_v2_1_17 mdm_v3_2_15 proc_sys_reset_v5_0_13 axi_intc_v4_1_12 xlconcat_v2_1_1)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "ps_example.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/home/shubham/Xilinx2018.3/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_clk_wiz_0/ps_example_clk_wiz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_clk_wiz_0/ps_example_clk_wiz_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_const_1_0/sim/ps_example_const_1_0.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_operator_s.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_operator_s_coarsebkb.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_operator_s_gradiecud.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_top_CNTRL_s_axi.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_top_mul_18ns_31s_dEe.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_top_mul_mul_13ns_eOg.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/832b/hdl/verilog/data_source_top.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_data_source_0/sim/ps_example_data_source_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/af00/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_chan_ctrl_reg_0/sim/ps_example_chan_ctrl_reg_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reg_0/sim/ps_example_dec_ctrl_reg_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_hard_data_reg_0/sim/ps_example_hard_data_reg_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tdata_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tuser_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tstrb_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tkeep_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tid_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tdest_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/tlast_ps_example_dec_ctrl_reinterpret_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/33dd/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/hdl/top_ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_reinterpret_0/sim/ps_example_dec_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_src_data_broadcast_0/hdl/tdata_ps_example_src_data_broadcast_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_src_data_broadcast_0/hdl/tuser_ps_example_src_data_broadcast_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_broadcaster_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/52f6/hdl/axis_broadcaster_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_src_data_broadcast_0/hdl/top_ps_example_src_data_broadcast_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_src_data_broadcast_0/sim/ps_example_src_data_broadcast_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_data_fifo_v2_0_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/4efd/hdl/axis_data_fifo_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_src_data_fifo_0/sim/ps_example_src_data_fifo_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_chan_ctrl_fifo_0/sim/ps_example_chan_ctrl_fifo_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ctrl_fifo_0/sim/ps_example_dec_ctrl_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work ecc_v2_0_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/690a/hdl/ecc_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fec_5g_common_v1_1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl/fec_5g_common_v1_1_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work polar_v1_0_2 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/2b35/hdl/polar_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_polar_enc_0/sim/ps_example_polar_enc_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_const_16_0/sim/ps_example_enc_const_16_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_const_12_0/sim/ps_example_enc_const_12_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_clock_converter_v1_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/b823/hdl/axis_clock_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_0/sim/ps_example_auto_cc_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tdata_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tuser_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tstrb_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tkeep_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tid_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tdest_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/tlast_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/hdl/top_ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_0/sim/ps_example_auto_ss_slid_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_1/sim/ps_example_auto_cc_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tdata_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tuser_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tstrb_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tkeep_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tid_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tdest_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/tlast_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/hdl/top_ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_0/sim/ps_example_auto_ss_k_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_2/sim/ps_example_auto_cc_2.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tdata_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tuser_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tstrb_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tkeep_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tid_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tdest_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/tlast_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/hdl/top_ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ctrl_reinterpret_0/sim/ps_example_enc_ctrl_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tdata_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tuser_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tstrb_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tkeep_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tid_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tdest_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/tlast_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/hdl/top_ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_reinterpret_0/sim/ps_example_enc_data_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_data_fifo_0/sim/ps_example_enc_data_fifo_0.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_imag1.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_imag2.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_imag3.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_imag4.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real1.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real1_coarsebkb.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real1_gradiecud.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real1_scaleLdEe.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real2.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real3.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/awgn_real4.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_meOg.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_mFfa.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_mfYi.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_mGfk.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_QBew.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_QCeG.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_QDeQ.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x_QEe0.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6d58/hdl/verilog/mod_and_chan_4x.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_mod_and_chan_0/sim/ps_example_mod_and_chan_0.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_4x_mul_mul_ibs.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_4x_mul_mul_jbC.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_4x_mul_mul_kbM.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_4x_mul_mul_lbW.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_4x_mux_83_2Hfu.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demodbkb.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demodcud.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demoddEe.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demodeOg.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demodfYi.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demodg8j.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func1_demodhbi.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func2.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func3.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_func4.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/05f6/hdl/verilog/demod_4x.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_demod_0/sim/ps_example_demod_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_dwidth_converter_v1_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/4ca6/hdl/axis_dwidth_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reshape_0/sim/ps_example_llr_reshape_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tdata_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tuser_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tstrb_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tkeep_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tid_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tdest_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/tlast_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/hdl/top_ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_llr_reinterpret_0/sim/ps_example_llr_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_hard_chan_data_fifo_0/sim/ps_example_hard_chan_data_fifo_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_polar_dec_0/sim/ps_example_polar_dec_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_3/sim/ps_example_auto_cc_3.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tdata_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tuser_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tstrb_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tkeep_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tid_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tdest_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/tlast_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/hdl/top_ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_slid_1/sim/ps_example_auto_ss_slid_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_4/sim/ps_example_auto_cc_4.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tdata_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tuser_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tstrb_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tkeep_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tid_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tdest_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/tlast_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/hdl/top_ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_ss_k_1/sim/ps_example_auto_ss_k_1.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_5/sim/ps_example_auto_cc_5.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tdata_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tuser_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tstrb_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tkeep_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tid_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tdest_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/tlast_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/hdl/top_ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_stat_reinterpret_0/sim/ps_example_dec_stat_reinterpret_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_6/sim/ps_example_auto_cc_6.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_const_12_0/sim/ps_example_dec_const_12_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_const_16_0/sim/ps_example_dec_const_16_0.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/e20c/hdl/verilog/stats_num_diff.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/e20c/hdl/verilog/stats_num_diff_bit_cnt_V.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/e20c/hdl/verilog/stats_top_CNTRL_s_axi.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/e20c/hdl/verilog/stats_top.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_stats_0/sim/ps_example_stats_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_20 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a7c9/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_axi_gpio_0/sim/ps_example_axi_gpio_0.vhd" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_gpio_reset_0/sim/ps_example_gpio_reset_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/f3db/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_reset_slice_0/sim/ps_example_reset_slice_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/0da8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/cbdd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a04b/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/87fb/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6b5f/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_gate_bit_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/693f/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_counter_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/0952/hdl/xbip_counter_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_counter_binary_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/c366/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_rtc_0/sim/ps_example_rtc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/3563/hdl/verilog/monitor_CNTRL_s_axi.v" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/3563/hdl/verilog/monitor.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ip_mon_0/sim/ps_example_enc_ip_mon_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ipshared/1196/axis_probe.vhd" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_ip_probe_0/sim/ps_example_enc_ip_probe_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_op_mon_0/sim/ps_example_enc_op_mon_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_enc_op_probe_0/sim/ps_example_enc_op_probe_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ip_mon_0/sim/ps_example_dec_ip_mon_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_ip_probe_0/sim/ps_example_dec_ip_probe_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_op_mon_0/sim/ps_example_dec_op_mon_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dec_op_probe_0/sim/ps_example_dec_op_probe_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v11_0_0 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/2ed1/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_microblaze_ps_0/sim/ps_example_microblaze_ps_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/78eb/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dlmb_v10_0/sim/ps_example_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_ilmb_v10_0/sim/ps_example_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/92fd/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_dlmb_bram_if_cntlr_0/sim/ps_example_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_ilmb_bram_if_cntlr_0/sim/ps_example_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/37c2/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_lmb_bram_0/sim/ps_example_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/cc23/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/64f4/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_3 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/64f4/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/c4fd/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/6c9d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_xbar_0/sim/ps_example_xbar_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m00_regslice_0/sim/ps_example_m00_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m01_regslice_0/sim/ps_example_m01_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m02_regslice_0/sim/ps_example_m02_regslice_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/693a/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_7/sim/ps_example_auto_cc_7.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m03_regslice_0/sim/ps_example_m03_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m04_regslice_0/sim/ps_example_m04_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m05_regslice_0/sim/ps_example_m05_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_auto_cc_8/sim/ps_example_auto_cc_8.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m06_regslice_0/sim/ps_example_m06_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m07_regslice_0/sim/ps_example_m07_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m08_regslice_0/sim/ps_example_m08_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m09_regslice_0/sim/ps_example_m09_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m10_regslice_0/sim/ps_example_m10_regslice_0.v" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_m11_regslice_0/sim/ps_example_m11_regslice_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work mdm_v3_2_15 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/41ef/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_mdm_1_0/sim/ps_example_mdm_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_rst_clk_wiz_100M_0/sim/ps_example_rst_clk_wiz_100M_0.vhd" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_rst_clk_wiz_200M_0/sim/ps_example_rst_clk_wiz_200M_0.vhd" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_rst_clk_wiz_150M_0/sim/ps_example_rst_clk_wiz_150M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_12 $vhdlan_opts \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/31e4/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_axi_intc_0/sim/ps_example_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/85a3" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/a023/hdl" +incdir+"$ref_dir/../../../../polar_0_ex.srcs/sources_1/bd/ps_example/ipshared/ec67/hdl" +incdir+"/home/shubham/Xilinx2018.3/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/ps_example/ip/ps_example_concat_int_0/sim/ps_example_concat_int_0.v" \
    "$ref_dir/../../../bd/ps_example/sim/ps_example.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.ps_example xil_defaultlib.glbl -o ps_example_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./ps_example_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./ps_example.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key ps_example_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc ps_example_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./ps_example.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: ps_example.sh [-help]\n\
Usage: ps_example.sh [-lib_map_path]\n\
Usage: ps_example.sh [-reset_run]\n\
Usage: ps_example.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
