#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

/* Definitions for bus frequencies */
#define XPAR_CPU_M_AXI_DP_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
/******************************************************************/

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000
#define XPAR_MICROBLAZE_CORE_CLOCK_FREQ_HZ 100000000

/******************************************************************/


/* Definitions for peripheral MICROBLAZE_PS */
#define XPAR_MICROBLAZE_PS_ADDR_SIZE 32
#define XPAR_MICROBLAZE_PS_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_PS_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_PS_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_PS_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_PS_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_PS_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_PS_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_PS_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_PS_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_PS_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_PS_DADDR_SIZE 32
#define XPAR_MICROBLAZE_PS_DATA_SIZE 32
#define XPAR_MICROBLAZE_PS_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_PS_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_PS_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_PS_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_PS_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_PS_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_PS_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_PS_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_PS_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_PS_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_PS_DC_AXI_MON 0
#define XPAR_MICROBLAZE_PS_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_PS_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_PS_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_PS_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_PS_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_PS_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_PS_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_PS_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_PS_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_PS_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_DP_AXI_MON 0
#define XPAR_MICROBLAZE_PS_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_PS_D_AXI 1
#define XPAR_MICROBLAZE_PS_D_LMB 1
#define XPAR_MICROBLAZE_PS_D_LMB_MON 0
#define XPAR_MICROBLAZE_PS_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_PS_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_PS_ENDIANNESS 1
#define XPAR_MICROBLAZE_PS_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_PS_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_FREQ 100000000
#define XPAR_MICROBLAZE_PS_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_FSL_LINKS 0
#define XPAR_MICROBLAZE_PS_IADDR_SIZE 32
#define XPAR_MICROBLAZE_PS_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_PS_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_PS_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_PS_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_PS_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_PS_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_PS_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_PS_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_PS_IC_AXI_MON 0
#define XPAR_MICROBLAZE_PS_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_PS_INSTR_SIZE 32
#define XPAR_MICROBLAZE_PS_INTERCONNECT 2
#define XPAR_MICROBLAZE_PS_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_PS_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_PS_IP_AXI_MON 0
#define XPAR_MICROBLAZE_PS_I_AXI 0
#define XPAR_MICROBLAZE_PS_I_LMB 1
#define XPAR_MICROBLAZE_PS_I_LMB_MON 0
#define XPAR_MICROBLAZE_PS_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_PS_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_PS_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_PS_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_PS_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_PS_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_PS_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_PS_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_PS_MMU_ZONES 16
#define XPAR_MICROBLAZE_PS_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_PS_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_PS_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_PS_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_PS_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_PS_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_PS_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_PS_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_PS_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_PS_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_PS_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_PS_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_PS_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_PS_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_PS_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_PS_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_PS_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_PS_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_PS_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_PS_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_PS_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_PS_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PS_PC_WIDTH 32
#define XPAR_MICROBLAZE_PS_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PS_PVR 0
#define XPAR_MICROBLAZE_PS_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PS_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_PS_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_PS_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_PS_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_PS_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_PS_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_PS_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_PS_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_PS_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_PS_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_PS_SCO 0
#define XPAR_MICROBLAZE_PS_TRACE 0
#define XPAR_MICROBLAZE_PS_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_PS_USE_BARREL 0
#define XPAR_MICROBLAZE_PS_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_PS_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_PS_USE_DCACHE 0
#define XPAR_MICROBLAZE_PS_USE_DIV 0
#define XPAR_MICROBLAZE_PS_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_PS_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_PS_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_PS_USE_FPU 0
#define XPAR_MICROBLAZE_PS_USE_HW_MUL 0
#define XPAR_MICROBLAZE_PS_USE_ICACHE 0
#define XPAR_MICROBLAZE_PS_USE_INTERRUPT 1
#define XPAR_MICROBLAZE_PS_USE_MMU 0
#define XPAR_MICROBLAZE_PS_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_PS_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_PS_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_PS_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_PS_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_PS_COMPONENT_NAME ps_example_microblaze_ps_0
#define XPAR_MICROBLAZE_PS_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_PS_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_PS_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_PS_G_USE_EXCEPTIONS 0

/******************************************************************/

#define XPAR_CPU_ID 0
#define XPAR_MICROBLAZE_ID 0
#define XPAR_MICROBLAZE_ADDR_SIZE 32
#define XPAR_MICROBLAZE_ADDR_TAG_BITS 17
#define XPAR_MICROBLAZE_ALLOW_DCACHE_WR 1
#define XPAR_MICROBLAZE_ALLOW_ICACHE_WR 1
#define XPAR_MICROBLAZE_AREA_OPTIMIZED 0
#define XPAR_MICROBLAZE_ASYNC_INTERRUPT 1
#define XPAR_MICROBLAZE_ASYNC_WAKEUP 3
#define XPAR_MICROBLAZE_AVOID_PRIMITIVES 0
#define XPAR_MICROBLAZE_BASE_VECTORS 0x0000000000000000
#define XPAR_MICROBLAZE_BRANCH_TARGET_CACHE_SIZE 0
#define XPAR_MICROBLAZE_CACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DADDR_SIZE 32
#define XPAR_MICROBLAZE_DATA_SIZE 32
#define XPAR_MICROBLAZE_DCACHE_ADDR_TAG 17
#define XPAR_MICROBLAZE_DCACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_DCACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_DCACHE_BYTE_SIZE 8192
#define XPAR_MICROBLAZE_DCACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_DCACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_DCACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_DCACHE_VICTIMS 0
#define XPAR_MICROBLAZE_DC_AXI_MON 0
#define XPAR_MICROBLAZE_DEBUG_COUNTER_WIDTH 32
#define XPAR_MICROBLAZE_DEBUG_ENABLED 1
#define XPAR_MICROBLAZE_DEBUG_EVENT_COUNTERS 5
#define XPAR_MICROBLAZE_DEBUG_EXTERNAL_TRACE 0
#define XPAR_MICROBLAZE_DEBUG_INTERFACE 0
#define XPAR_MICROBLAZE_DEBUG_LATENCY_COUNTERS 1
#define XPAR_MICROBLAZE_DEBUG_PROFILE_SIZE 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_ASYNC_RESET 0
#define XPAR_MICROBLAZE_DEBUG_TRACE_SIZE 8192
#define XPAR_MICROBLAZE_DIV_ZERO_EXCEPTION 0
#define XPAR_MICROBLAZE_DP_AXI_MON 0
#define XPAR_MICROBLAZE_DYNAMIC_BUS_SIZING 0
#define XPAR_MICROBLAZE_D_AXI 1
#define XPAR_MICROBLAZE_D_LMB 1
#define XPAR_MICROBLAZE_D_LMB_MON 0
#define XPAR_MICROBLAZE_ECC_USE_CE_EXCEPTION 0
#define XPAR_MICROBLAZE_EDGE_IS_POSITIVE 1
#define XPAR_MICROBLAZE_ENABLE_DISCRETE_PORTS 0
#define XPAR_MICROBLAZE_ENDIANNESS 1
#define XPAR_MICROBLAZE_FAULT_TOLERANT 0
#define XPAR_MICROBLAZE_FPU_EXCEPTION 0
#define XPAR_MICROBLAZE_FREQ 100000000
#define XPAR_MICROBLAZE_FSL_EXCEPTION 0
#define XPAR_MICROBLAZE_FSL_LINKS 0
#define XPAR_MICROBLAZE_IADDR_SIZE 32
#define XPAR_MICROBLAZE_ICACHE_ALWAYS_USED 0
#define XPAR_MICROBLAZE_ICACHE_BASEADDR 0x00000000
#define XPAR_MICROBLAZE_ICACHE_DATA_WIDTH 0
#define XPAR_MICROBLAZE_ICACHE_FORCE_TAG_LUTRAM 0
#define XPAR_MICROBLAZE_ICACHE_HIGHADDR 0x3FFFFFFF
#define XPAR_MICROBLAZE_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_ICACHE_STREAMS 0
#define XPAR_MICROBLAZE_ICACHE_VICTIMS 0
#define XPAR_MICROBLAZE_IC_AXI_MON 0
#define XPAR_MICROBLAZE_ILL_OPCODE_EXCEPTION 0
#define XPAR_MICROBLAZE_IMPRECISE_EXCEPTIONS 0
#define XPAR_MICROBLAZE_INSTR_SIZE 32
#define XPAR_MICROBLAZE_INTERCONNECT 2
#define XPAR_MICROBLAZE_INTERRUPT_IS_EDGE 0
#define XPAR_MICROBLAZE_INTERRUPT_MON 0
#define XPAR_MICROBLAZE_IP_AXI_MON 0
#define XPAR_MICROBLAZE_I_AXI 0
#define XPAR_MICROBLAZE_I_LMB 1
#define XPAR_MICROBLAZE_I_LMB_MON 0
#define XPAR_MICROBLAZE_LMB_DATA_SIZE 32
#define XPAR_MICROBLAZE_LOCKSTEP_MASTER 0
#define XPAR_MICROBLAZE_LOCKSTEP_SELECT 0
#define XPAR_MICROBLAZE_LOCKSTEP_SLAVE 0
#define XPAR_MICROBLAZE_M0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_M15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_MMU_DTLB_SIZE 4
#define XPAR_MICROBLAZE_MMU_ITLB_SIZE 2
#define XPAR_MICROBLAZE_MMU_PRIVILEGED_INSTR 0
#define XPAR_MICROBLAZE_MMU_TLB_ACCESS 3
#define XPAR_MICROBLAZE_MMU_ZONES 16
#define XPAR_MICROBLAZE_M_AXI_DC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_DC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DC_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_DC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_DC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_DP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_DP_EXCLUSIVE_ACCESS 0
#define XPAR_MICROBLAZE_M_AXI_DP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_D_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_M_AXI_IC_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_ARUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_AWUSER_WIDTH 5
#define XPAR_MICROBLAZE_M_AXI_IC_BUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IC_RUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IC_USER_SIGNALS 0
#define XPAR_MICROBLAZE_M_AXI_IC_USER_VALUE 31
#define XPAR_MICROBLAZE_M_AXI_IC_WUSER_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_IP_ADDR_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_DATA_WIDTH 32
#define XPAR_MICROBLAZE_M_AXI_IP_THREAD_ID_WIDTH 1
#define XPAR_MICROBLAZE_M_AXI_I_BUS_EXCEPTION 0
#define XPAR_MICROBLAZE_NUMBER_OF_PC_BRK 1
#define XPAR_MICROBLAZE_NUMBER_OF_RD_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUMBER_OF_WR_ADDR_BRK 0
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_DEBUG 2
#define XPAR_MICROBLAZE_NUM_SYNC_FF_CLK_IRQ 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_CLK 1
#define XPAR_MICROBLAZE_NUM_SYNC_FF_DBG_TRACE_CLK 2
#define XPAR_MICROBLAZE_OPCODE_0X0_ILLEGAL 0
#define XPAR_MICROBLAZE_OPTIMIZATION 0
#define XPAR_MICROBLAZE_PC_WIDTH 32
#define XPAR_MICROBLAZE_PIADDR_SIZE 32
#define XPAR_MICROBLAZE_PVR 0
#define XPAR_MICROBLAZE_PVR_USER1 0x00
#define XPAR_MICROBLAZE_PVR_USER2 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR 0x00000000
#define XPAR_MICROBLAZE_RESET_MSR_BIP 0
#define XPAR_MICROBLAZE_RESET_MSR_DCE 0
#define XPAR_MICROBLAZE_RESET_MSR_EE 0
#define XPAR_MICROBLAZE_RESET_MSR_EIP 0
#define XPAR_MICROBLAZE_RESET_MSR_ICE 0
#define XPAR_MICROBLAZE_RESET_MSR_IE 0
#define XPAR_MICROBLAZE_S0_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S0_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S1_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S1_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S2_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S2_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S3_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S3_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S4_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S4_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S5_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S5_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S6_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S6_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S7_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S7_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S8_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S8_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S9_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S9_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S10_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S10_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S11_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S11_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S12_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S12_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S13_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S13_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S14_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S14_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_S15_AXIS_DATA_WIDTH 32
#define XPAR_MICROBLAZE_S15_AXIS_PROTOCOL GENERIC
#define XPAR_MICROBLAZE_SCO 0
#define XPAR_MICROBLAZE_TRACE 0
#define XPAR_MICROBLAZE_UNALIGNED_EXCEPTIONS 0
#define XPAR_MICROBLAZE_USE_BARREL 0
#define XPAR_MICROBLAZE_USE_BRANCH_TARGET_CACHE 0
#define XPAR_MICROBLAZE_USE_CONFIG_RESET 0
#define XPAR_MICROBLAZE_USE_DCACHE 0
#define XPAR_MICROBLAZE_USE_DIV 0
#define XPAR_MICROBLAZE_USE_EXTENDED_FSL_INSTR 0
#define XPAR_MICROBLAZE_USE_EXT_BRK 0
#define XPAR_MICROBLAZE_USE_EXT_NM_BRK 0
#define XPAR_MICROBLAZE_USE_FPU 0
#define XPAR_MICROBLAZE_USE_HW_MUL 0
#define XPAR_MICROBLAZE_USE_ICACHE 0
#define XPAR_MICROBLAZE_USE_INTERRUPT 1
#define XPAR_MICROBLAZE_USE_MMU 0
#define XPAR_MICROBLAZE_USE_MSR_INSTR 0
#define XPAR_MICROBLAZE_USE_NON_SECURE 0
#define XPAR_MICROBLAZE_USE_PCMP_INSTR 0
#define XPAR_MICROBLAZE_USE_REORDER_INSTR 1
#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0
#define XPAR_MICROBLAZE_COMPONENT_NAME ps_example_microblaze_ps_0
#define XPAR_MICROBLAZE_EDK_IPTYPE PROCESSOR
#define XPAR_MICROBLAZE_EDK_SPECIAL microblaze
#define XPAR_MICROBLAZE_G_TEMPLATE_LIST 0
#define XPAR_MICROBLAZE_G_USE_EXCEPTIONS 0

/******************************************************************/

#define STDIN_BASEADDRESS 0x41400000
#define STDOUT_BASEADDRESS 0x41400000

/******************************************************************/

/* Platform specific definitions */
#define PLATFORM_MB
 
/* Definitions for sleep timer configuration */
#define XSLEEP_TIMER_IS_DEFAULT_TIMER
 
 
/******************************************************************/
/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 2U

/* Definitions for peripheral MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x000FFFFFU
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU 
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU 


/* Definitions for peripheral MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID 1U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DATA_WIDTH 32U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_FAULT_INJECT 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_STATUS_REGISTERS 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_CE_COUNTER_WIDTH 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_WRITE_ACCESS 2U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_BASEADDR 0x00000000U
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_HIGHADDR 0x000FFFFFU
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_BASEADDR 0xFFFFFFFFU 
#define XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_S_AXI_CTRL_HIGHADDR 0xFFFFFFFFU 


/******************************************************************/

/* Canonical definitions for peripheral MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_0_DEVICE_ID XPAR_MICROBLAZE_PS_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 32U
#define XPAR_BRAM_0_ECC 0U
#define XPAR_BRAM_0_FAULT_INJECT 0U
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_0_WRITE_ACCESS 2U
#define XPAR_BRAM_0_BASEADDR 0x00000000U
#define XPAR_BRAM_0_HIGHADDR 0x000FFFFFU

/* Canonical definitions for peripheral MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR */
#define XPAR_BRAM_1_DEVICE_ID XPAR_MICROBLAZE_PS_LOCAL_MEMORY_ILMB_BRAM_IF_CNTLR_DEVICE_ID
#define XPAR_BRAM_1_DATA_WIDTH 32U
#define XPAR_BRAM_1_ECC 0U
#define XPAR_BRAM_1_FAULT_INJECT 0U
#define XPAR_BRAM_1_CE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_UE_FAILING_REGISTERS 0U
#define XPAR_BRAM_1_ECC_STATUS_REGISTERS 0U
#define XPAR_BRAM_1_CE_COUNTER_WIDTH 0U
#define XPAR_BRAM_1_ECC_ONOFF_REGISTER 0U
#define XPAR_BRAM_1_ECC_ONOFF_RESET_VALUE 1U
#define XPAR_BRAM_1_WRITE_ACCESS 2U
#define XPAR_BRAM_1_BASEADDR 0x00000000U
#define XPAR_BRAM_1_HIGHADDR 0x000FFFFFU


/******************************************************************/

/* Definitions for driver DATA_SOURCE_TOP */
#define XPAR_XDATA_SOURCE_TOP_NUM_INSTANCES 1

/* Definitions for peripheral DATA_SOURCE */
#define XPAR_DATA_SOURCE_DEVICE_ID 0
#define XPAR_DATA_SOURCE_S_AXI_CNTRL_BASEADDR 0x44A00000
#define XPAR_DATA_SOURCE_S_AXI_CNTRL_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Canonical definitions for peripheral DATA_SOURCE */
#define XPAR_XDATA_SOURCE_TOP_0_DEVICE_ID XPAR_DATA_SOURCE_DEVICE_ID
#define XPAR_XDATA_SOURCE_TOP_0_S_AXI_CNTRL_BASEADDR 0x44A00000
#define XPAR_XDATA_SOURCE_TOP_0_S_AXI_CNTRL_HIGHADDR 0x44A0FFFF


/******************************************************************/

/* Definitions for driver GPIO */
#define XPAR_XGPIO_NUM_INSTANCES 2

/* Definitions for peripheral AXI_GPIO */
#define XPAR_AXI_GPIO_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_HIGHADDR 0x4000FFFF
#define XPAR_AXI_GPIO_DEVICE_ID 0
#define XPAR_AXI_GPIO_INTERRUPT_PRESENT 0
#define XPAR_AXI_GPIO_IS_DUAL 0


/* Definitions for peripheral GPIO_RESET */
#define XPAR_GPIO_RESET_BASEADDR 0x40010000
#define XPAR_GPIO_RESET_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_RESET_DEVICE_ID 1
#define XPAR_GPIO_RESET_INTERRUPT_PRESENT 0
#define XPAR_GPIO_RESET_IS_DUAL 0


/******************************************************************/

/* Canonical definitions for peripheral AXI_GPIO */
#define XPAR_GPIO_0_BASEADDR 0x40000000
#define XPAR_GPIO_0_HIGHADDR 0x4000FFFF
#define XPAR_GPIO_0_DEVICE_ID XPAR_AXI_GPIO_DEVICE_ID
#define XPAR_GPIO_0_INTERRUPT_PRESENT 0
#define XPAR_GPIO_0_IS_DUAL 0

/* Canonical definitions for peripheral GPIO_RESET */
#define XPAR_GPIO_1_BASEADDR 0x40010000
#define XPAR_GPIO_1_HIGHADDR 0x4001FFFF
#define XPAR_GPIO_1_DEVICE_ID XPAR_GPIO_RESET_DEVICE_ID
#define XPAR_GPIO_1_INTERRUPT_PRESENT 0
#define XPAR_GPIO_1_IS_DUAL 0


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 2
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral AXI_INTC */
#define XPAR_AXI_INTC_DEVICE_ID 0
#define XPAR_AXI_INTC_BASEADDR 0x41200000
#define XPAR_AXI_INTC_HIGHADDR 0x4120FFFF
#define XPAR_AXI_INTC_KIND_OF_INTR 0xFFFFFFFF
#define XPAR_AXI_INTC_HAS_FAST 0
#define XPAR_AXI_INTC_IVAR_RESET_VALUE 0x0000000000000010
#define XPAR_AXI_INTC_NUM_INTR_INPUTS 2
#define XPAR_AXI_INTC_ADDR_WIDTH 32


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x41200000
#define XPAR_INTC_SINGLE_HIGHADDR 0x4120FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_AXI_INTC_DEVICE_ID
#define XPAR_AXI_INTC_TYPE 0U
#define XPAR_POLAR_ENC_INTERRUPT_MASK 0X000001U
#define XPAR_AXI_INTC_POLAR_ENC_INTERRUPT_INTR 0U
#define XPAR_POLAR_DEC_INTERRUPT_MASK 0X000002U
#define XPAR_AXI_INTC_POLAR_DEC_INTERRUPT_INTR 1U

/******************************************************************/

/* Canonical definitions for peripheral AXI_INTC */
#define XPAR_INTC_0_DEVICE_ID XPAR_AXI_INTC_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x41200000U
#define XPAR_INTC_0_HIGHADDR 0x4120FFFFU
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFFU
#define XPAR_INTC_0_HAS_FAST 0U
#define XPAR_INTC_0_IVAR_RESET_VALUE 0x0000000000000010U
#define XPAR_INTC_0_NUM_INTR_INPUTS 2U
#define XPAR_INTC_0_ADDR_WIDTH 32U
#define XPAR_INTC_0_INTC_TYPE 0U

#define XPAR_INTC_0_POLAR_1_VEC_ID XPAR_AXI_INTC_POLAR_ENC_INTERRUPT_INTR
#define XPAR_INTC_0_POLAR_0_VEC_ID XPAR_AXI_INTC_POLAR_DEC_INTERRUPT_INTR

/******************************************************************/

/* Definitions for driver MONITOR */
#define XPAR_XMONITOR_NUM_INSTANCES 4

/* Definitions for peripheral DEC_IP_MON */
#define XPAR_DEC_IP_MON_DEVICE_ID 0
#define XPAR_DEC_IP_MON_S_AXI_CNTRL_BASEADDR 0x44AC0000
#define XPAR_DEC_IP_MON_S_AXI_CNTRL_HIGHADDR 0x44ACFFFF


/* Definitions for peripheral DEC_OP_MON */
#define XPAR_DEC_OP_MON_DEVICE_ID 1
#define XPAR_DEC_OP_MON_S_AXI_CNTRL_BASEADDR 0x44AD0000
#define XPAR_DEC_OP_MON_S_AXI_CNTRL_HIGHADDR 0x44ADFFFF


/* Definitions for peripheral ENC_IP_MON */
#define XPAR_ENC_IP_MON_DEVICE_ID 2
#define XPAR_ENC_IP_MON_S_AXI_CNTRL_BASEADDR 0x44A10000
#define XPAR_ENC_IP_MON_S_AXI_CNTRL_HIGHADDR 0x44A1FFFF


/* Definitions for peripheral ENC_OP_MON */
#define XPAR_ENC_OP_MON_DEVICE_ID 3
#define XPAR_ENC_OP_MON_S_AXI_CNTRL_BASEADDR 0x44A20000
#define XPAR_ENC_OP_MON_S_AXI_CNTRL_HIGHADDR 0x44A2FFFF


/******************************************************************/

/* Canonical definitions for peripheral DEC_IP_MON */
#define XPAR_XMONITOR_0_DEVICE_ID XPAR_DEC_IP_MON_DEVICE_ID
#define XPAR_XMONITOR_0_S_AXI_CNTRL_BASEADDR 0x44AC0000
#define XPAR_XMONITOR_0_S_AXI_CNTRL_HIGHADDR 0x44ACFFFF

/* Canonical definitions for peripheral DEC_OP_MON */
#define XPAR_XMONITOR_1_DEVICE_ID XPAR_DEC_OP_MON_DEVICE_ID
#define XPAR_XMONITOR_1_S_AXI_CNTRL_BASEADDR 0x44AD0000
#define XPAR_XMONITOR_1_S_AXI_CNTRL_HIGHADDR 0x44ADFFFF

/* Canonical definitions for peripheral ENC_IP_MON */
#define XPAR_XMONITOR_2_DEVICE_ID XPAR_ENC_IP_MON_DEVICE_ID
#define XPAR_XMONITOR_2_S_AXI_CNTRL_BASEADDR 0x44A10000
#define XPAR_XMONITOR_2_S_AXI_CNTRL_HIGHADDR 0x44A1FFFF

/* Canonical definitions for peripheral ENC_OP_MON */
#define XPAR_XMONITOR_3_DEVICE_ID XPAR_ENC_OP_MON_DEVICE_ID
#define XPAR_XMONITOR_3_S_AXI_CNTRL_BASEADDR 0x44A20000
#define XPAR_XMONITOR_3_S_AXI_CNTRL_HIGHADDR 0x44A2FFFF


/******************************************************************/

/* Definitions for driver POLAR */
#define XPAR_XPOLAR_NUM_INSTANCES 2

/* Definitions for peripheral POLAR_DEC */
#define XPAR_POLAR_DEC_DEVICE_ID 0
#define XPAR_POLAR_DEC_S_AXI_BASEADDR 0x44A80000
#define XPAR_POLAR_DEC_S_AXI_HIGHADDR 0x44ABFFFF
#define XPAR_POLAR_DEC_DRV_INITIALIZATION_PARAMS 0


/* Definitions for peripheral POLAR_ENC */
#define XPAR_POLAR_ENC_DEVICE_ID 1
#define XPAR_POLAR_ENC_S_AXI_BASEADDR 0x44A40000
#define XPAR_POLAR_ENC_S_AXI_HIGHADDR 0x44A7FFFF
#define XPAR_POLAR_ENC_DRV_INITIALIZATION_PARAMS 0


/******************************************************************/

/* Canonical definitions for peripheral POLAR_DEC */
#define XPAR_XPOLAR_0_DEVICE_ID XPAR_POLAR_DEC_DEVICE_ID
#define XPAR_XPOLAR_0_S_AXI_BASEADDR 0x44A80000
#define XPAR_XPOLAR_0_S_AXI_HIGHADDR 0x44ABFFFF
#define XPAR_XPOLAR_0_DRV_INITIALIZATION_PARAMS 0

/* Canonical definitions for peripheral POLAR_ENC */
#define XPAR_XPOLAR_1_DEVICE_ID XPAR_POLAR_ENC_DEVICE_ID
#define XPAR_XPOLAR_1_S_AXI_BASEADDR 0x44A40000
#define XPAR_XPOLAR_1_S_AXI_HIGHADDR 0x44A7FFFF
#define XPAR_XPOLAR_1_DRV_INITIALIZATION_PARAMS 0


/******************************************************************/

/* Definitions for driver STATS_TOP */
#define XPAR_XSTATS_TOP_NUM_INSTANCES 1

/* Definitions for peripheral STATS */
#define XPAR_STATS_DEVICE_ID 0
#define XPAR_STATS_S_AXI_CNTRL_BASEADDR 0x44A30000
#define XPAR_STATS_S_AXI_CNTRL_HIGHADDR 0x44A3FFFF


/******************************************************************/

/* Canonical definitions for peripheral STATS */
#define XPAR_XSTATS_TOP_0_DEVICE_ID XPAR_STATS_DEVICE_ID
#define XPAR_XSTATS_TOP_0_S_AXI_CNTRL_BASEADDR 0x44A30000
#define XPAR_XSTATS_TOP_0_S_AXI_CNTRL_HIGHADDR 0x44A3FFFF


/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral MDM_1 */
#define XPAR_MDM_1_BASEADDR 0x41400000
#define XPAR_MDM_1_HIGHADDR 0x41400FFF
#define XPAR_MDM_1_DEVICE_ID 0
#define XPAR_MDM_1_BAUDRATE 0
#define XPAR_MDM_1_USE_PARITY 0
#define XPAR_MDM_1_ODD_PARITY 0
#define XPAR_MDM_1_DATA_BITS 0


/******************************************************************/

/* Canonical definitions for peripheral MDM_1 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_MDM_1_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x41400000
#define XPAR_UARTLITE_0_HIGHADDR 0x41400FFF
#define XPAR_UARTLITE_0_BAUDRATE 0
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 0


/******************************************************************/

#endif  /* end of protection macro */
