webtalk_init -webtalk_dir /home/shubham/Vivado_Exercises/edt_zcu102/edt_zcu102.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-12-27 19:41:57" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211528478_1777544339_210704364_923" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "mgme9ai637t8c5bhlob7so13sp" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_14" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4298.289 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.646 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1577455630000" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key isZynqMP -value "true" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key Processors -value "7" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key Arch -value "zynquplus" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key Device -value "xczu9eg" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1577455630000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1577455917246"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1577455917246"
webtalk_transmit -clientid 1019917131 -regid "211528478_1777544339_210704364_923" -xml /home/shubham/Vivado_Exercises/edt_zcu102/edt_zcu102.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/shubham/Vivado_Exercises/edt_zcu102/edt_zcu102.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/shubham/Vivado_Exercises/edt_zcu102/edt_zcu102.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
