# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/edt_zcu102/edt_zcu102.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102 || ORIG_REF_NAME==edt_zcu102} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_zynq_ultra_ps_e_0_0/edt_zcu102_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==edt_zcu102_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_axi_timer_0_0/edt_zcu102_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_timer_0_0 || ORIG_REF_NAME==edt_zcu102_axi_timer_0_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_0_0/edt_zcu102_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_gpio_0_0 || ORIG_REF_NAME==edt_zcu102_axi_gpio_0_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_1_0/edt_zcu102_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_gpio_1_0 || ORIG_REF_NAME==edt_zcu102_axi_gpio_1_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_xbar_0/edt_zcu102_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_xbar_0 || ORIG_REF_NAME==edt_zcu102_xbar_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_ps8_0_axi_periph_0/edt_zcu102_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_ps8_0_axi_periph_0 || ORIG_REF_NAME==edt_zcu102_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_rst_ps8_0_99M_0/edt_zcu102_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_rst_ps8_0_99M_0 || ORIG_REF_NAME==edt_zcu102_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_auto_ds_0/edt_zcu102_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_auto_ds_0 || ORIG_REF_NAME==edt_zcu102_auto_ds_0} -quiet] -quiet

# IP: bd/edt_zcu102/ip/edt_zcu102_auto_pc_0/edt_zcu102_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==edt_zcu102_auto_pc_0 || ORIG_REF_NAME==edt_zcu102_auto_pc_0} -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_zynq_ultra_ps_e_0_0/edt_zcu102_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: bd/edt_zcu102/ip/edt_zcu102_zynq_ultra_ps_e_0_0/edt_zcu102_zynq_ultra_ps_e_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==edt_zcu102_zynq_ultra_ps_e_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_timer_0_0/edt_zcu102_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_timer_0_0 || ORIG_REF_NAME==edt_zcu102_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_timer_0_0/edt_zcu102_axi_timer_0_0_ooc.xdc

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_0_0/edt_zcu102_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_gpio_0_0 || ORIG_REF_NAME==edt_zcu102_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_0_0/edt_zcu102_axi_gpio_0_0_ooc.xdc

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_0_0/edt_zcu102_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_gpio_0_0 || ORIG_REF_NAME==edt_zcu102_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_1_0/edt_zcu102_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_gpio_1_0 || ORIG_REF_NAME==edt_zcu102_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_1_0/edt_zcu102_axi_gpio_1_0_ooc.xdc

# XDC: bd/edt_zcu102/ip/edt_zcu102_axi_gpio_1_0/edt_zcu102_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_axi_gpio_1_0 || ORIG_REF_NAME==edt_zcu102_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_rst_ps8_0_99M_0/edt_zcu102_rst_ps8_0_99M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_rst_ps8_0_99M_0 || ORIG_REF_NAME==edt_zcu102_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_rst_ps8_0_99M_0/edt_zcu102_rst_ps8_0_99M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_rst_ps8_0_99M_0 || ORIG_REF_NAME==edt_zcu102_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_auto_ds_0/edt_zcu102_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==edt_zcu102_auto_ds_0 || ORIG_REF_NAME==edt_zcu102_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/edt_zcu102/ip/edt_zcu102_auto_ds_0/edt_zcu102_auto_ds_0_ooc.xdc

# XDC: bd/edt_zcu102/ip/edt_zcu102_auto_pc_0/edt_zcu102_auto_pc_0_ooc.xdc

# XDC: bd/edt_zcu102/edt_zcu102_ooc.xdc
