# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/design_1_system_ila_1_3.xci
# IP: The module: 'design_1_system_ila_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/bd_371d.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_371d || ORIG_REF_NAME==bd_371d} -quiet] -quiet

# IP: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/bd_371d_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_371d_ila_lib_0 || ORIG_REF_NAME==bd_371d_ila_lib_0} -quiet] -quiet

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_371d_ila_lib_0 || ORIG_REF_NAME==bd_371d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_371d_ila_lib_0 || ORIG_REF_NAME==bd_371d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/bd_371d_ila_lib_0_ooc.xdc

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/bd_371d_ooc.xdc

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/design_1_system_ila_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_1_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/design_1_system_ila_1_3.xci
# IP: The module: 'design_1_system_ila_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/bd_371d.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_371d || ORIG_REF_NAME==bd_371d} -quiet] -quiet

# IP: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/bd_371d_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_371d_ila_lib_0 || ORIG_REF_NAME==bd_371d_ila_lib_0} -quiet] -quiet

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_371d_ila_lib_0 || ORIG_REF_NAME==bd_371d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_371d_ila_lib_0 || ORIG_REF_NAME==bd_371d_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/ip/ip_0/bd_371d_ila_lib_0_ooc.xdc

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/bd_0/bd_371d_ooc.xdc

# XDC: /home/shubham/Vivado_Exercises/project_7/project_7.srcs/sources_1/bd/design_1/ip/design_1_system_ila_1_3/design_1_system_ila_1_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
