#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Wed Feb 05 15:11:37 IST 2020
# SW Build 2405991 on Thu Dec  6 23:36:41 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
echo "xvlog --incr --relax -L fec_5g_common_v1_1_0 -L polar_v1_0_2 -L axi_vip_v1_1_4 -L zynq_ultra_ps_e_vip_v1_0_4 -L xilinx_vip -prj tb_vlog.prj"
ExecStep xvlog --incr --relax -L fec_5g_common_v1_1_0 -L polar_v1_0_2 -L axi_vip_v1_1_4 -L zynq_ultra_ps_e_vip_v1_0_4 -L xilinx_vip -prj tb_vlog.prj 2>&1 | tee compile.log

echo "xvhdl --incr --relax -prj tb_vhdl.prj"
ExecStep xvhdl --incr --relax -prj tb_vhdl.prj 2>&1 | tee -a compile.log

